// ---------------------------------------------------------------------------
// marker-icons.ts — マーカーアイコン定義（lucide-react版）
// RankingForm / RankingCard / RankingDetailContent 等が共有するアイコンリスト。
// ---------------------------------------------------------------------------

import type { ComponentType } from "react";
import {
  Heart,
  Star,
  Music4,
  Book,
  Disc,
  Film,
  Tv,
  Sun,
  Moon,
  Cloud,
  Leaf,
  Smile,
  Coffee,
  Circle,
  Flame,
  Zap,
  Sparkles,
  Flower,
  Flower2,
  Cherry,
  Apple,
  IceCream,
  Cake,
  Pizza,
  Gift,
  Camera,
  Palette,
  Gamepad2,
  Headphones,
  Crown,
  Gem,
  Feather,
  Anchor,
  Compass,
  Map,
  Mountain,
  Tent,
  Bike,
  Car,
  Plane,
  Rocket,
  Umbrella,
  Snowflake,
  Droplets,
  Bird,
  Cat,
  Dog,
  Fish,
  Rabbit,
  PawPrint,
  TreePine,
  TreeDeciduous,
  Sprout,
  Sunrise,
  Sunset,
  Rainbow,
  Wine,
  Utensils,
  Cookie,
  IceCream2,
  Ticket,
  Music,
  Music2,
  Music3,
  type LucideProps,
} from "lucide-react";

// LucideIcon 型（コンポーネント型）
export type LucideIconType = ComponentType<LucideProps>;

// アイコン名 → コンポーネントのマッピング
const ICON_MAP: Record<string, LucideIconType> = {
  Heart,
  Star,
  Music4,
  Book,
  Disc,
  Film,
  Tv,
  Sun,
  Moon,
  Cloud,
  Leaf,
  Smile,
  Coffee,
  Flame,
  Zap,
  Sparkles,
  Flower,
  Flower2,
  Cherry,
  Apple,
  IceCream,
  Cake,
  Pizza,
  Gift,
  Camera,
  Palette,
  Gamepad2,
  Headphones,
  Crown,
  Gem,
  Feather,
  Anchor,
  Compass,
  Map,
  Mountain,
  Tent,
  Bike,
  Car,
  Plane,
  Rocket,
  Umbrella,
  Snowflake,
  Droplets,
  Bird,
  Cat,
  Dog,
  Fish,
  Rabbit,
  PawPrint,
  TreePine,
  TreeDeciduous,
  Sprout,
  Sunrise,
  Sunset,
  Rainbow,
  Wine,
  Utensils,
  Cookie,
  IceCream2,
  Ticket,
  Music,
  Music2,
  Music3,
};

// アイコン一覧（選択UI用）
export const MARKER_ICONS: { name: string; label: string }[] = [
  { name: "Heart", label: "ハート" },
  { name: "Star", label: "スター" },
  { name: "Music4", label: "ミュージック" },
  { name: "Book", label: "ブック" },
  { name: "Disc", label: "ディスク" },
  { name: "Film", label: "フィルム" },
  { name: "Tv", label: "テレビ" },
  { name: "Sun", label: "サン" },
  { name: "Moon", label: "ムーン" },
  { name: "Cloud", label: "クラウド" },
  { name: "Leaf", label: "リーフ" },
  { name: "Smile", label: "スマイル" },
  { name: "Coffee", label: "コーヒー" },
  { name: "Flame", label: "炎" },
  { name: "Zap", label: "稲妻" },
  { name: "Sparkles", label: "きらきら" },
  { name: "Flower", label: "花" },
  { name: "Flower2", label: "花びら" },
  { name: "Cherry", label: "さくらんぼ" },
  { name: "Apple", label: "りんご" },
  { name: "IceCream", label: "アイス" },
  { name: "Cake", label: "ケーキ" },
  { name: "Pizza", label: "ピザ" },
  { name: "Gift", label: "ギフト" },
  { name: "Camera", label: "カメラ" },
  { name: "Palette", label: "パレット" },
  { name: "Gamepad2", label: "ゲーム" },
  { name: "Headphones", label: "ヘッドホン" },
  { name: "Crown", label: "王冠" },
  { name: "Gem", label: "宝石" },
  { name: "Feather", label: "羽根" },
  { name: "Anchor", label: "いかり" },
  { name: "Compass", label: "コンパス" },
  { name: "Map", label: "地図" },
  { name: "Mountain", label: "山" },
  { name: "Tent", label: "テント" },
  { name: "Bike", label: "自転車" },
  { name: "Car", label: "車" },
  { name: "Plane", label: "飛行機" },
  { name: "Rocket", label: "ロケット" },
  { name: "Umbrella", label: "傘" },
  { name: "Snowflake", label: "雪" },
  { name: "Droplets", label: "しずく" },
  { name: "Bird", label: "鳥" },
  { name: "Cat", label: "猫" },
  { name: "Dog", label: "犬" },
  { name: "Fish", label: "魚" },
  { name: "Rabbit", label: "うさぎ" },
  { name: "PawPrint", label: "肉球" },
  { name: "TreePine", label: "針葉樹" },
  { name: "TreeDeciduous", label: "広葉樹" },
  { name: "Sprout", label: "芽" },
  { name: "Sunrise", label: "日の出" },
  { name: "Sunset", label: "夕焼け" },
  { name: "Rainbow", label: "虹" },
  { name: "Wine", label: "ワイン" },
  { name: "Utensils", label: "食器" },
  { name: "Cookie", label: "クッキー" },
  { name: "IceCream2", label: "ソフトクリーム" },
  { name: "Ticket", label: "チケット" },
  { name: "Music", label: "音符" },
  { name: "Music2", label: "メロディ" },
  { name: "Music3", label: "音楽" },
];

/**
 * アイコン名からlucide-reactコンポーネントを返す。
 * 未知の名前の場合は Circle をフォールバックとして返す（後方互換性のため Heart も可）。
 */
export function getMarkerIcon(name: string): LucideIconType {
  return ICON_MAP[name] ?? Circle;
}
