// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOdHAeEq0Ibg3zvvv3DYoMU49zfJyZ0Fo',
    appId: '1:550323251580:web:b676382e22228fd9b45cf9',
    messagingSenderId: '550323251580',
    projectId: 'my-home-manual',
    authDomain: 'my-home-manual.firebaseapp.com',
    storageBucket: 'my-home-manual.firebasestorage.app',
    measurementId: 'G-G8DKWNE4M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASSyytsYeryaa_mb19ChrvetRq2hnu3I4',
    appId: '1:550323251580:android:edc2ea2b18031e42b45cf9',
    messagingSenderId: '550323251580',
    projectId: 'my-home-manual',
    storageBucket: 'my-home-manual.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBslmfJjlOYn9L5fN8qrKXHD-rZHdC7N1I',
    appId: '1:550323251580:ios:796a3deaaa1ac658b45cf9',
    messagingSenderId: '550323251580',
    projectId: 'my-home-manual',
    storageBucket: 'my-home-manual.firebasestorage.app',
    iosClientId: '550323251580-03os6cq0a6ej60btvmmttlbanpld4mm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.uchiNoManual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBslmfJjlOYn9L5fN8qrKXHD-rZHdC7N1I',
    appId: '1:550323251580:ios:796a3deaaa1ac658b45cf9',
    messagingSenderId: '550323251580',
    projectId: 'my-home-manual',
    storageBucket: 'my-home-manual.firebasestorage.app',
    iosClientId: '550323251580-03os6cq0a6ej60btvmmttlbanpld4mm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.uchiNoManual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOdHAeEq0Ibg3zvvv3DYoMU49zfJyZ0Fo',
    appId: '1:550323251580:web:a526cca7663f0701b45cf9',
    messagingSenderId: '550323251580',
    projectId: 'my-home-manual',
    authDomain: 'my-home-manual.firebaseapp.com',
    storageBucket: 'my-home-manual.firebasestorage.app',
    measurementId: 'G-31SSF92E02',
  );
}
