// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgipRPMz1p0iJPrlzbhfex4hL7fGvUQb8',
    appId: '1:151396203786:web:ea3d827d4c2f9227cecef3',
    messagingSenderId: '151396203786',
    projectId: 'develop-practice-e7579',
    authDomain: 'develop-practice-e7579.firebaseapp.com',
    storageBucket: 'develop-practice-e7579.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYNgy9KcGLPTRPfiTxOnefflTwZ-qNzCk',
    appId: '1:151396203786:android:17b0d774ad4424dccecef3',
    messagingSenderId: '151396203786',
    projectId: 'develop-practice-e7579',
    storageBucket: 'develop-practice-e7579.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB6F-q_N3G94TlqhZfP61d-QB7hbRvYJg',
    appId: '1:151396203786:ios:3da4d596254c08cececef3',
    messagingSenderId: '151396203786',
    projectId: 'develop-practice-e7579',
    storageBucket: 'develop-practice-e7579.firebasestorage.app',
    iosBundleId: 'com.example.uchiNoManual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB6F-q_N3G94TlqhZfP61d-QB7hbRvYJg',
    appId: '1:151396203786:ios:3da4d596254c08cececef3',
    messagingSenderId: '151396203786',
    projectId: 'develop-practice-e7579',
    storageBucket: 'develop-practice-e7579.firebasestorage.app',
    iosBundleId: 'com.example.uchiNoManual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgipRPMz1p0iJPrlzbhfex4hL7fGvUQb8',
    appId: '1:151396203786:web:85824864e015f4d9cecef3',
    messagingSenderId: '151396203786',
    projectId: 'develop-practice-e7579',
    authDomain: 'develop-practice-e7579.firebaseapp.com',
    storageBucket: 'develop-practice-e7579.firebasestorage.app',
  );
}
